{
 "title": "Stiebel Eltron",
 "description": "Charts displaying various metrics such as power, load, autonomy and energy",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "influxdb" },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "buckets()\r\n  |> filter(fn: (r) => r.name != \"_monitoring\" and r.name != \"_tasks\")"
   },
   {
    "name": "site",
    "label": "Site",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"${bucket}\",\r\n    tag: \"site\",\r\n    predicate: (r) => true,\r\n    start: -180d\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Room Temperature HC 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_room_temperature_heating_circuit\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc1\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_room_temperature_heating_circuit\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc1\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Room Temperature HC 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_room_temperature_heating_circuit\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc2\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_room_temperature_heating_circuit\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc2\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Heating Temperature HC 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc1\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc1\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Heating Temperature HC 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc2\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.circuit == \"hc2\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_outside_temperature\" and\r\n    r.site == \"${site}\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\": r._value, _time: r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Domestic Hotwater Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_domestic_hotwater_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_domestic_hotwater_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Condenser Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_general_temperature_condenser\" and\r\n    r.site == \"${site}\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Buffer Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_buffer_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Actual\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_buffer_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.state == \"target\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Target\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Flow Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_flow_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.type == \"heatpump\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Heatpump\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_flow_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.type == \"reheating\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Reheating\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_heating_flow_temperature\" and\r\n    r.site == \"${site}\" and\r\n    r.type == \"preflow\" and\r\n    r.state == \"actual\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Pre-Flow\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  { "title": "Pump Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Pump Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_general_output_activity_ratio\" and\r\n    r.site == \"${site}\" and\r\n    r.pump == \"heat\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Heat Pump\":r._value, _time:r._time}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_general_output_activity_ratio\" and\r\n    r.site == \"${site}\" and\r\n    r.pump == \"water\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Water Pump\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Circuit Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_general_heating_circuit_pressure\" and\r\n    r.site == \"${site}\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Pressure\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  {
   "title": "Compressor Duration Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_process_data_compressor_delay_counter\" and\r\n    r.site == \"${site}\"\r\n  )\r\n  |> group(columns: [\"site\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\"Compressor Duration Timer\":r._value, _time:r._time}))\r\n"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Energy per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\nimport \"date\"\r\n\r\ndividyByX = (x, tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({\r\n        r with\r\n        _value: r._value / x\r\n      })\r\n    )\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_energy_heating_total\" and\r\n    r.site == \"${site}\" and\r\n    r.compressor == \"heating\" and\r\n    r.timeframe == \"day\"\r\n  )\r\n  |> drop(columns: [\"url\", \"host\", \"timeframe\"])\r\n  |> window(every: 24h)\r\n  |> max()\r\n  |> group(columns: [\"site\"])\r\n  |> dividyByX(x: 3600.0)\r\n  |> map(fn: (r) => ({\"Compressor\": r._value, _time: date.truncate(t: r._time, unit: 1d)}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\nimport \"date\"\r\n\r\ndividyByX = (x, tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({\r\n        r with\r\n        _value: r._value / x\r\n      })\r\n    )\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_energy_heating_total\" and\r\n    r.site == \"${site}\" and\r\n    r.compressor == \"domestic_hotwater\" and\r\n    r.timeframe == \"day\"\r\n  )\r\n  |> drop(columns: [\"url\", \"host\", \"timeframe\"])\r\n  |> window(every: 24h)\r\n  |> max()\r\n  |> group(columns: [\"site\"])\r\n  |> dividyByX(x: 3600.0)\r\n  |> map(fn: (r) => ({\"Domestic Hotwater\": r._value, _time: date.truncate(t: r._time, unit: 1d)}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Energy per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "dividyByX = (x, tables=<-) =>\r\n  tables\r\n    |> map(fn: (r) => ({\r\n        r with\r\n        _value: r._value / x\r\n      })\r\n    )\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_energy_heating_total\" and\r\n    r.site == \"${site}\" and\r\n    r.timeframe == \"day\"\r\n  )\r\n  |> pivot(\r\n    rowKey: [\"_time\"],\r\n    columnKey: [\"compressor\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => (\r\n    {_value: r.domestic_hotwater + r.heating, _time: r._time}\r\n  ))\r\n  |> window(every: 24h)\r\n  |> max()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> mean()\r\n  |> dividyByX(x: 3600.0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Total Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_runtime_compressor\" and\r\n    r.site == \"${site}\" and\r\n    r.compressor == \"heating\"\r\n  )\r\n  |> last()\r\n  |> map(fn: (r) => ({\"Heating\": r._value}))\r\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) =>\r\n    r._measurement == \"stiebeleltron_runtime_compressor\" and\r\n    r.site == \"${site}\" and\r\n    r.compressor == \"domestic_hotwater\"\r\n  )\r\n  |> last()\r\n  |> map(fn: (r) => ({\"Domestic Hotwater\": r._value}))\r\n"
    }
   ]
  }
 ]
}