# Default values for fronius-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Usually `1` is fine
replicaCount: 1

image:
  # image.registry -- Container image registry
  registry: docker.io
  # image.repository -- Location of the container image
  repository: ccremer/fronius-exporter
  # image.tag -- Container image tag
  tag: "v0.3.0"
  pullPolicy: IfNotPresent

# imagePullSecrets -- List of image pull secrets if you use a privately hosted image
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

fronius:
  # fronius.url -- Target URL of Fronius SYMO device. **Required**
  url: "http://symo.ip.or.hostname/solar_api/v1/GetPowerFlowRealtimeData.fcgi"
  # fronius.additionalArgs -- Provide additional CLI flags via string array
  additionalArgs: []
  # fronius.timeoutSeconds -- Time after which collecting may time out. Should not be higher than
  # the Prometheus scrape interval.
  timeoutSeconds: 5

serviceAccount:
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the service account to use.
  # If not set and `create` is `true`, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # service.type -- Service type
  type: ClusterIP
  # service.port -- Service port number
  port: 8080
  # service.nodePort -- Node port number if `type` is `NodePort`
  nodePort: 0

ingress:
  # ingress.enabled -- Useful if your Prometheus is outside of the cluster
  enabled: false
  # ingress.annotations -- Additional annotations for the Ingress object
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # ingress.hosts -- See Kubernetes Docs for a guide to setup Ingress hosts
  hosts: []
  # ingress.hosts -- See Kubernetes Docs for a guide to setup TLS on Ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 64Mi
  requests:
    cpu: 20m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
