{{- if not .Values.ssh.externalSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "znapzend.fullname" . }}
  labels:
    {{- include "znapzend.labels" . | nindent 4 }}
stringData:
  {{- with .Values.ssh.knownHosts }}
  known_hosts: |
  {{- range . }}
    {{ .host }} {{ .pubKey }}
  {{ end }}
  {{- end }}
  {{- with .Values.ssh.config }}
  config: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- range $key,$value := .Values.ssh.identities }}
  {{ $key -}}: {{ $value | toYaml | indent 2 }}
  {{- end }}
{{- end }}
