{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "znapzend.fullname" . }}
  labels:
    {{- include "znapzend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "znapzend.selectorLabels" . | nindent 4 }}
{{- end }}
