apiVersion: apps/v1
kind: Statefulset
metadata:
  name: {{ include "znapzend.fullname" . }}
  labels:
    {{- include "znapzend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "znapzend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "znapzend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
              - pidof
              - znapzend
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        {{ if .Values.metrics.enabled }}
        - name: exporter
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
          {{- if .Values.metrics.jobs }}
            - name: JOBS_REGISTER
              value: "{{ .Values.metrics.jobs | join "," }}"
          {{ end }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 5

        {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: zfs
          hostPath:
            path: "{{ .Values.host.zfsDevice }}"
            type: CharDevice
