apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stiebeleltron-exporter.fullname" . }}
  labels:
    {{- include "stiebeleltron-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stiebeleltron-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.telegraf.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.telegraf.enabled }}
        app.kubernetes.io/checksum: telegraf={{ include (print $.Template.BasePath "/telegraf-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "stiebeleltron-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stiebeleltron-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "stiebeleltron-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --isg.url={{ .Values.exporter.isgUrl }}
            - --isg.timeout={{ .Values.exporter.timeoutSeconds }}
            {{- range .Values.exporter.additionalArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.telegraf.enabled }}
        - name: telegraf
          image: {{ include "stiebeleltron-exporter.telegrafImage" . }}
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
      volumes:
        - name: telegraf-config
          secret:
            secretName: {{ template "stiebeleltron-exporter.fullname" . }}
            defaultMode: 420
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
      {{- range $ip, $hostnames := . }}
        - ip: {{ $ip }}
          hostnames:
          {{- range . }}
            - {{ . }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
