apiVersion: v1
kind: Service
metadata:
  name: {{ include "stiebeleltron-exporter.fullname" . }}
  labels:
    {{- include "stiebeleltron-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "stiebeleltron-exporter.selectorLabels" . | nindent 4 }}
