# Default values for fronius-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Usually `1` is fine
replicaCount: 1

image:
  # -- Container image registry
  registry: docker.io
  # -- Location of the container image
  repository: ccremer/fronius-exporter
  # -- Container image tag
  tag: "v0.3.0"
  pullPolicy: IfNotPresent

# -- List of image pull secrets if you use a privately hosted image
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

fronius:
  # -- Target URL of Fronius SYMO device. **Required**
  url: "http://symo.ip.or.hostname/solar_api/v1/GetPowerFlowRealtimeData.fcgi"
  # -- Provide additional CLI flags via string array
  additionalArgs: []
  # -- Time after which collecting may time out. Should not be higher than
  # the Prometheus scrape interval.
  timeoutSeconds: 5

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and `create` is `true`, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Service type
  type: ClusterIP
  # -- Service port number
  port: 8080
  # -- Node port number if `type` is `NodePort`
  nodePort: 0

ingress:
  # -- Useful if your Prometheus is outside of the cluster
  enabled: false
  # -- Additional annotations for the Ingress object
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # -- See Kubernetes Docs for a guide to setup Ingress hosts
  hosts: []
  # -- See Kubernetes Docs for a guide to setup TLS on Ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 64Mi
  requests:
    cpu: 20m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
