apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sickchill.fullname" . }}
  labels:
    {{- include "sickchill.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sickchill.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sickchill.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sickchill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "sickchill.containerImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.sickchill.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.downloads.enabled }}
            - mountPath: /downloads
              name: downloads
            {{- end }}
            {{- if .Values.persistence.shows.enabled }}
            - mountPath: /shows
              name: shows
            {{- end }}
            {{- if .Values.persistence.data.enabled }}
            - mountPath: /data
              name: data
            {{- end }}
          {{- with .Values.persistence.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.downloads.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ include "sickchill.fullname" . }}-downloads
        {{- end }}
        {{- if .Values.persistence.shows.enabled }}
        - name: shows
          persistentVolumeClaim:
            claimName: {{ include "sickchill.fullname" . }}-shows
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "sickchill.fullname" . }}-data
        {{- end }}
      {{- with .Values.persistence.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
