# Default values for znapzend.

replicaCount: 1

image:
  repository: docker.io/oetiker/znapzend
  tag: master
  pullPolicy: IfNotPresent
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # The current image requires to run privileged in order to access ZFS
  allowPrivilegeEscalation: true
  privileged: true

resources: {}

host:
  zfsDevice: /dev/zfs

ssh:
  path: /root/.ssh
# config: |
#   Host my-host
#     IdentityFile ~/.ssh/my-id
#     User myuser
# externalSecretName: my-own-ssh-secret
  identities: {}
#   id_ed25519: |
#     -----BEGIN OPENSSH PRIVATE KEY-----
#     ...
#     -----END OPENSSH PRIVATE KEY-----
# knownHosts:
#   - host: my-host
#     pubKey: ssh-ed25519 AAAAC3NzaC...

metrics:
  enabled: true
  jobs:
    register: []
  env: {}

  image:
    repository: docker.io/braindoctor/znapzend-exporter
    tag: v0.1.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
