{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  {{- with .Values.cronjob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "nextcloud.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- if (default .Values.image.pullSecrets .Values.cronjob.image.pullSecrets) }}
          imagePullSecrets:
          {{- range (default .Values.image.pullSecrets .Values.cronjob.image.pullSecrets) }}
            - name: {{ . }}
          {{- end }}
          {{- end }}
          containers:
            - name: background
              image: "{{ default .Values.image.repository .Values.cronjob.image.repository }}:{{ default .Values.image.tag .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ default .Values.image.pullPolicy .Values.cronjob.image.pullPolicy }}
              command: [ "curl" ]
              args:
                - "--fail"
                - "-L"
                - "-H"
                - "Host: {{ .Values.nextcloud.host }}"
                - "http://{{ include "nextcloud.fullname" . }}/cron.php"
              resources:
                {{- toYaml (default .Values.resources .Values.cronjob.resources) | nindent 16 }}
          {{- with (default .Values.nodeSelector .Values.cronjob.nodeSelector) }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.affinity .Values.cronjob.affinity) }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (default .Values.tolerations .Values.cronjob.tolerations) }}
          tolerations:
          {{- toYaml . | nindent 12 }}:
          {{- end }}
{{- end }}
