{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.database.password | b64enc | quote }}
  db-username: {{ default "" .Values.database.user | b64enc | quote }}

  nextcloud-username: {{ .Values.nextcloud.username | b64enc | quote }}
  {{ if .Values.nextcloud.password }}
  nextcloud-password: {{ .Values.nextcloud.password | b64enc | quote }}
  {{ else }}
  nextcloud-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}

  {{- if .Values.nextcloud.mail.enabled }}
  smtp-username: {{ default "" .Values.nextcloud.mail.smtp.name | b64enc | quote }}
  smtp-password: {{ default "" .Values.nextcloud.mail.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
