{{- if .Values.grafana.datasource.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stiebeleltron-stack.fullname" . }}-datasource
  namespace: {{ default .Release.Namespace .Values.grafana.datasource.namespace }}
  labels:
    {{- include "stiebeleltron-stack.labels" . | nindent 4 }}
    {{- toYaml .Values.grafana.datasource.labels | nindent 4}}
  {{- if .Values.grafana.datasource.annotations }}
  annotations:
    {{- toYaml .Values.grafana.datasource.annotations | nindent 4 }}
  {{- end }}
stringData:
  {{ template "stiebeleltron-stack.fullname" . }}.yaml: |-
    apiVersion: 1
    datasources:
    - name: {{ template "stiebeleltron-stack.fullname" . }}
      type: influxdb
      url: {{ include "stiebeleltron-stack.influxdb-host" . }}
      isDefault: false
      secureJsonData:
        token: {{ .Values.stiebeleltron.telegraf.influxdb.token }}
      jsonData:
        httpMode: POST
        timeInterval: {{ .Values.stiebeleltron.telegraf.interval }}
        version: Flux
        defaultBucket: {{ .Values.stiebeleltron.telegraf.influxdb.bucket }}
        organization: {{ .Values.stiebeleltron.telegraf.influxdb.organization }}
{{- end -}}
