{{- if .Values.telegraf.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fronius-exporter.fullname" . }}
  labels:
    {{- include "fronius-exporter.labels" . | nindent 4 }}
stringData:
  telegraf.conf: |
    [[inputs.prometheus]]
      urls = ["http://localhost:8080/metrics"]
      interval = {{ .Values.telegraf.interval | quote }}
      fielddrop = ["url"]
    [[outputs.influxdb_v2]]
      urls = [{{ .Values.telegraf.influxdb.url | quote }}]
      token = {{ .Values.telegraf.influxdb.token | quote }}
      organization = {{ .Values.telegraf.influxdb.organization | quote }}
      bucket = {{ .Values.telegraf.influxdb.bucket | quote }}
    [global_tags]
      hostname = "$HOSTNAME"
{{- end -}}
