{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-zfs-provisioner.fullname" . }}-binding
  labels:
    {{- include "kubernetes-zfs-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-zfs-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-zfs-provisioner.fullname" . }}-leaderelection
  labels:
    {{- include "kubernetes-zfs-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpoint-controller
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-zfs-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
