name: Lint

on:
  pull_request: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Lint unit tests
        run: make lint

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Chart documentation
        run: make docs
      - name: Check if documentation is on par with Chart changes
        run: git diff --exit-code

  chart-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Verify chart versions have been updated
        run: make lint:versions
