name: Test

on:
  push:
    branches-ignore:
    - master
    pull_request:
      types: [opened, reopened]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.8'

    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod

    - name: Run Chart unit tests
      run: |
        find . -type f -name go.mod | xargs -I % bash -c 'cd "$(dirname %)" && go test ./...'
