name: Test

on:
  pull_request: {}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Prepare charts
        run: make prepare
      - name: Run Chart unit tests
        run: make test
