name: Test

on:
  push:
    branches-ignore:
    - master
    pull_request:
      types: [opened, reopened]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: azure/setup-helm@v1
      with:
        version: v3.1.2

    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'

    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod

    - name: Run Chart unit tests
      run: |
        find . -type f -name go.mod | xargs -I % bash -c 'cd "$(dirname %)" && go test ./...'

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check if documentation is on par with Chart changes
        run: .ci/helm-docs.sh
